title: Data 88E
description: Economic Models
author: UC Berkeley
baseurl: ~ # the subpath of your site, e.g. /blog
url: 'https://data88e.org' # the base hostname & protocol for your site, e.g. http://example.com

# Theme settings
remote_theme: "just-the-docs/just-the-docs@v0.10.1"
plugins:
  - jekyll-remote-theme
color_scheme: light
search_enabled: true
permalink: pretty
search_enabled: false

icon: assets/images/blue_text.png